version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: echo tag and branch
          command: |
            if [[ "$CIRCLE_TAG" && ! "$CIRCLE_BRANCH" ]]; then
              CIRCLE_BRANCH=$(git branch --contains tags/${CIRCLE_TAG} | awk '{print $2}')
            fi
            if [[ "$CIRCLE_BRANCH" = "master" && "$CIRCLE_TAG" ]]; then
              DOCKER_TAG=latest
              DOCKER_TAG2=$CIRCLE_TAG
            elif [[ "$CIRCLE_BRANCH" = "master" ]]; then
              DOCKER_TAG=latest
              DOCKER_TAG2="build-${CIRCLE_BUILD_NUM}"
            elif [[ "$CIRCLE_TAG" = "deploy-dev" ]]; then
              DOCKER_TAG="deploy-dev-${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}"
            elif [[ "$CIRCLE_TAG" = "deploy-staging" ]]; then
              DOCKER_TAG="deploy-staging-${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}"
            elif [[ "$CIRCLE_TAG" ]]; then
              DOCKER_TAG=$CIRCLE_TAG
            else
              DOCKER_TAG=$CIRCLE_BRANCH
              DOCKER_TAG2="${CIRCLE_BRANCH}-build-${CIRCLE_BUILD_NUM}"
            fi
            echo "tag is: " $DOCKER_TAG
            if [[ "$DOCKER_TAG2" ]]; then
              echo "tag2 is: " $DOCKER_TAG2
            fi
  deploy-dev:
    docker:
      - image: docker:stable
    steps:
      - run:
          name: Placeholder for deploy dev
          command: |
            echo "placeholder for deploying image: deploy-dev-${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH} to dev environment"
  deploy-staging:
    docker:
      - image: docker:stable
    steps:
      - run:
          name: Placeholder for deploy staging
          command: |
            echo "placeholder for deploying image: deploy-staging-${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH} to staging environment"


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-dev:
          requires:
            - build
          filters:
            tags:
              only: deploy-dev
            branches:
              ignore: /.*/
      - deploy-staging:
          requires:
            - build
          filters:
            tags:
              only: deploy-staging
            branches:
              ignore: /.*/

