version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: echo tag and branch
          command: |
            if [[ "$CIRCLE_BRANCH" = "master" && "$CIRCLE_TAG" ]]; then
              DOCKER_TAG=latest
              DOCKER_BUILD_TAG=$CIRCLE_TAG
            elif [[ "$CIRCLE_BRANCH" = "master" ]]; then
              DOCKER_TAG=latest
              DOCKER_BUILD_TAG="build-${CIRCLE_BUILD_NUM}"
            elif [[ "$CIRCLE_TAG" ]]; then
              DOCKER_TAG=$CIRCLE_TAG
              if [[ $CIRCLE_TAG =~ ^deploy-dev- ]]; then
                DOCKER_TAG=deploy-dev
                DOCKER_BUILD_TAG=$CIRCLE_TAG
              elif [[ $CIRCLE_TAG =~ ^deploy-staging- ]]; then
                DOCKER_TAG=deploy-staging
                DOCKER_BUILD_TAG=$CIRCLE_TAG
              fi
            elif [[ "$CIRCLE_BRANCH" = "deploy-prod" ]]; then
              DOCKER_TAG=deploy-prod
              DOCKER_BUILD_TAG="deploy-prod-build-${CIRCLE_BUILD_NUM}"
            else
              DOCKER_TAG=$CIRCLE_BRANCH
              DOCKER_BUILD_TAG="${CIRCLE_BRANCH}-build-${CIRCLE_BUILD_NUM}"
            fi
            echo "docker tag is: " $DOCKER_TAG
            if [[ "$DOCKER_BUILD_TAG" ]]; then
              echo "docker build tag is: " $DOCKER_BUILD_TAG
            fi
            mkdir -p /tmp/workspace
            echo $DOCKER_BUILD_TAG > /tmp/workspace/image_tag
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - image_tag
  deploy-dev:
    docker:
      - image: docker:stable
    steps:
      - run:
          name: Placeholder for deploy dev
          command: |
            echo "installing curl"
            apk update
            apk add curl
            echo "triggering circle ci build that would deploy image: $CIRCLE_TAG to dev environment"
            curl -u ${CIRCLE_API_TOKEN}: \
              --data build_parameters[CIRCLE_JOB]=deploy-dev \
              --data build_parameters[IMAGE_TAG]=${CIRCLE_TAG} \
              https://circleci.com/api/v1.1/project/github/FitnessKeeper/noss-circleci-test2/tree/deploy-dev
  deploy-staging:
    docker:
      - image: docker:stable
    steps:
      - run:
          name: Placeholder for deploy staging
          command: |
            echo "placeholder for deploying image: $CIRCLE_TAG to staging environment"
  deploy-prod:
    docker:
      - image: docker:stable
    steps:
      - attach_workspace:
         at: /tmp/workspace
      - run:
          name: Placeholder for deploy prod
          command: |
            echo "found tag: "
            cat /tmp/workspace/image_tag


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-dev:
          requires:
            - build
          filters:
            tags:
              only: /^deploy-dev-.*/
            branches:
              ignore: /.*/
      - deploy-staging:
          requires:
            - build
          filters:
            tags:
              only: /^deploy-staging-.*/
            branches:
              ignore: /.*/
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: deploy-prod
