version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: echo "hello world"
      - run:
          name: echo tag and branch
          command: |
            echo "Circle tag is: " $CIRCLE_TAG
            echo "Circle branch is: " $CIRCLE_BRANCH


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /v.*/