version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: echo tag and branch
          command: |
            if [[ "$CIRCLE_BRANCH" = "master" && "$CIRCLE_TAG" ]]; then
              DOCKER_TAG=latest
              DOCKER_TAG2=$CIRCLE_TAG
            elif [[ "$CIRCLE_BRANCH" = "master" ]]; then
              DOCKER_TAG=latest
              DOCKER_TAG2="build-${CIRCLE_BUILD_NUM}"
            elif [[ "$CIRCLE_TAG" ]]; then
              DOCKER_TAG=$CIRCLE_TAG
            else
              DOCKER_TAG=$CIRCLE_BRANCH
            fi
            echo "tag is: " $DOCKER_TAG
            if [ "$DOCKER_TAG2" ]; then
              echo "tag2 is: " $DOCKER_TAG2
            fi



workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v(\d+\.){2}\d+$/
